// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAdminDashboardBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final CardView cardViewAddBook;

  @NonNull
  public final CardView cardViewIssueRequest;

  @NonNull
  public final CardView cardViewIssuedBook;

  @NonNull
  public final CardView cardViewRecentHistory;

  @NonNull
  public final CardView cardViewReturnRequest;

  @NonNull
  public final LinearLayout main;

  private ActivityAdminDashboardBinding(@NonNull LinearLayout rootView,
      @NonNull CardView cardViewAddBook, @NonNull CardView cardViewIssueRequest,
      @NonNull CardView cardViewIssuedBook, @NonNull CardView cardViewRecentHistory,
      @NonNull CardView cardViewReturnRequest, @NonNull LinearLayout main) {
    this.rootView = rootView;
    this.cardViewAddBook = cardViewAddBook;
    this.cardViewIssueRequest = cardViewIssueRequest;
    this.cardViewIssuedBook = cardViewIssuedBook;
    this.cardViewRecentHistory = cardViewRecentHistory;
    this.cardViewReturnRequest = cardViewReturnRequest;
    this.main = main;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAdminDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAdminDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_admin_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAdminDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cardViewAddBook;
      CardView cardViewAddBook = ViewBindings.findChildViewById(rootView, id);
      if (cardViewAddBook == null) {
        break missingId;
      }

      id = R.id.cardViewIssueRequest;
      CardView cardViewIssueRequest = ViewBindings.findChildViewById(rootView, id);
      if (cardViewIssueRequest == null) {
        break missingId;
      }

      id = R.id.cardViewIssuedBook;
      CardView cardViewIssuedBook = ViewBindings.findChildViewById(rootView, id);
      if (cardViewIssuedBook == null) {
        break missingId;
      }

      id = R.id.cardViewRecentHistory;
      CardView cardViewRecentHistory = ViewBindings.findChildViewById(rootView, id);
      if (cardViewRecentHistory == null) {
        break missingId;
      }

      id = R.id.cardViewReturnRequest;
      CardView cardViewReturnRequest = ViewBindings.findChildViewById(rootView, id);
      if (cardViewReturnRequest == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      return new ActivityAdminDashboardBinding((LinearLayout) rootView, cardViewAddBook,
          cardViewIssueRequest, cardViewIssuedBook, cardViewRecentHistory, cardViewReturnRequest,
          main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
