// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import com.balysv.materialripple.MaterialRippleLayout;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAddBookBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final TextInputLayout baTextInputLayout;

  @NonNull
  public final TextInputLayout barcodeTextInputLayou;

  @NonNull
  public final TextInputLayout btTextInputLayout;

  @NonNull
  public final AppCompatButton btnUploadImage;

  @NonNull
  public final TextInputEditText editBarCodeNumber;

  @NonNull
  public final TextInputEditText editBookAuthor;

  @NonNull
  public final TextInputEditText editBookName;

  @NonNull
  public final TextInputEditText editBookType;

  @NonNull
  public final TextInputEditText editPlatformNo;

  @NonNull
  public final TextInputEditText editQuantity;

  @NonNull
  public final TextInputEditText editRackNo;

  @NonNull
  public final TextInputEditText editSide;

  @NonNull
  public final ImageView imgPhoto;

  @NonNull
  public final MaterialRippleLayout lytMaterialRLSubmit;

  @NonNull
  public final RelativeLayout main;

  @NonNull
  public final RelativeLayout rlSubmitBtnView;

  @NonNull
  public final TextInputLayout searchTextInputLayou;

  private ActivityAddBookBinding(@NonNull RelativeLayout rootView,
      @NonNull TextInputLayout baTextInputLayout, @NonNull TextInputLayout barcodeTextInputLayou,
      @NonNull TextInputLayout btTextInputLayout, @NonNull AppCompatButton btnUploadImage,
      @NonNull TextInputEditText editBarCodeNumber, @NonNull TextInputEditText editBookAuthor,
      @NonNull TextInputEditText editBookName, @NonNull TextInputEditText editBookType,
      @NonNull TextInputEditText editPlatformNo, @NonNull TextInputEditText editQuantity,
      @NonNull TextInputEditText editRackNo, @NonNull TextInputEditText editSide,
      @NonNull ImageView imgPhoto, @NonNull MaterialRippleLayout lytMaterialRLSubmit,
      @NonNull RelativeLayout main, @NonNull RelativeLayout rlSubmitBtnView,
      @NonNull TextInputLayout searchTextInputLayou) {
    this.rootView = rootView;
    this.baTextInputLayout = baTextInputLayout;
    this.barcodeTextInputLayou = barcodeTextInputLayou;
    this.btTextInputLayout = btTextInputLayout;
    this.btnUploadImage = btnUploadImage;
    this.editBarCodeNumber = editBarCodeNumber;
    this.editBookAuthor = editBookAuthor;
    this.editBookName = editBookName;
    this.editBookType = editBookType;
    this.editPlatformNo = editPlatformNo;
    this.editQuantity = editQuantity;
    this.editRackNo = editRackNo;
    this.editSide = editSide;
    this.imgPhoto = imgPhoto;
    this.lytMaterialRLSubmit = lytMaterialRLSubmit;
    this.main = main;
    this.rlSubmitBtnView = rlSubmitBtnView;
    this.searchTextInputLayou = searchTextInputLayou;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddBookBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddBookBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_add_book, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddBookBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.baTextInputLayout;
      TextInputLayout baTextInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (baTextInputLayout == null) {
        break missingId;
      }

      id = R.id.barcodeTextInputLayou;
      TextInputLayout barcodeTextInputLayou = ViewBindings.findChildViewById(rootView, id);
      if (barcodeTextInputLayou == null) {
        break missingId;
      }

      id = R.id.btTextInputLayout;
      TextInputLayout btTextInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (btTextInputLayout == null) {
        break missingId;
      }

      id = R.id.btnUploadImage;
      AppCompatButton btnUploadImage = ViewBindings.findChildViewById(rootView, id);
      if (btnUploadImage == null) {
        break missingId;
      }

      id = R.id.editBarCodeNumber;
      TextInputEditText editBarCodeNumber = ViewBindings.findChildViewById(rootView, id);
      if (editBarCodeNumber == null) {
        break missingId;
      }

      id = R.id.editBookAuthor;
      TextInputEditText editBookAuthor = ViewBindings.findChildViewById(rootView, id);
      if (editBookAuthor == null) {
        break missingId;
      }

      id = R.id.editBookName;
      TextInputEditText editBookName = ViewBindings.findChildViewById(rootView, id);
      if (editBookName == null) {
        break missingId;
      }

      id = R.id.editBookType;
      TextInputEditText editBookType = ViewBindings.findChildViewById(rootView, id);
      if (editBookType == null) {
        break missingId;
      }

      id = R.id.editPlatformNo;
      TextInputEditText editPlatformNo = ViewBindings.findChildViewById(rootView, id);
      if (editPlatformNo == null) {
        break missingId;
      }

      id = R.id.editQuantity;
      TextInputEditText editQuantity = ViewBindings.findChildViewById(rootView, id);
      if (editQuantity == null) {
        break missingId;
      }

      id = R.id.editRackNo;
      TextInputEditText editRackNo = ViewBindings.findChildViewById(rootView, id);
      if (editRackNo == null) {
        break missingId;
      }

      id = R.id.editSide;
      TextInputEditText editSide = ViewBindings.findChildViewById(rootView, id);
      if (editSide == null) {
        break missingId;
      }

      id = R.id.imgPhoto;
      ImageView imgPhoto = ViewBindings.findChildViewById(rootView, id);
      if (imgPhoto == null) {
        break missingId;
      }

      id = R.id.lytMaterialRLSubmit;
      MaterialRippleLayout lytMaterialRLSubmit = ViewBindings.findChildViewById(rootView, id);
      if (lytMaterialRLSubmit == null) {
        break missingId;
      }

      RelativeLayout main = (RelativeLayout) rootView;

      id = R.id.rl_submit_btn_view;
      RelativeLayout rlSubmitBtnView = ViewBindings.findChildViewById(rootView, id);
      if (rlSubmitBtnView == null) {
        break missingId;
      }

      id = R.id.searchTextInputLayou;
      TextInputLayout searchTextInputLayou = ViewBindings.findChildViewById(rootView, id);
      if (searchTextInputLayou == null) {
        break missingId;
      }

      return new ActivityAddBookBinding((RelativeLayout) rootView, baTextInputLayout,
          barcodeTextInputLayou, btTextInputLayout, btnUploadImage, editBarCodeNumber,
          editBookAuthor, editBookName, editBookType, editPlatformNo, editQuantity, editRackNo,
          editSide, imgPhoto, lytMaterialRLSubmit, main, rlSubmitBtnView, searchTextInputLayou);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
