// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final AppCompatButton btnLogin;

  @NonNull
  public final TextInputEditText editPassword;

  @NonNull
  public final TextInputEditText editUserName;

  @NonNull
  public final TextView forgotPasswordText;

  @NonNull
  public final TextInputLayout searchTextInputLayou;

  @NonNull
  public final TextInputLayout searchTextInputLayout;

  @NonNull
  public final TextView txtRegisterSwitchText;

  private ActivityLoginBinding(@NonNull LinearLayout rootView, @NonNull AppCompatButton btnLogin,
      @NonNull TextInputEditText editPassword, @NonNull TextInputEditText editUserName,
      @NonNull TextView forgotPasswordText, @NonNull TextInputLayout searchTextInputLayou,
      @NonNull TextInputLayout searchTextInputLayout, @NonNull TextView txtRegisterSwitchText) {
    this.rootView = rootView;
    this.btnLogin = btnLogin;
    this.editPassword = editPassword;
    this.editUserName = editUserName;
    this.forgotPasswordText = forgotPasswordText;
    this.searchTextInputLayou = searchTextInputLayou;
    this.searchTextInputLayout = searchTextInputLayout;
    this.txtRegisterSwitchText = txtRegisterSwitchText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnLogin;
      AppCompatButton btnLogin = ViewBindings.findChildViewById(rootView, id);
      if (btnLogin == null) {
        break missingId;
      }

      id = R.id.editPassword;
      TextInputEditText editPassword = ViewBindings.findChildViewById(rootView, id);
      if (editPassword == null) {
        break missingId;
      }

      id = R.id.editUserName;
      TextInputEditText editUserName = ViewBindings.findChildViewById(rootView, id);
      if (editUserName == null) {
        break missingId;
      }

      id = R.id.forgotPasswordText;
      TextView forgotPasswordText = ViewBindings.findChildViewById(rootView, id);
      if (forgotPasswordText == null) {
        break missingId;
      }

      id = R.id.searchTextInputLayou;
      TextInputLayout searchTextInputLayou = ViewBindings.findChildViewById(rootView, id);
      if (searchTextInputLayou == null) {
        break missingId;
      }

      id = R.id.searchTextInputLayout;
      TextInputLayout searchTextInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (searchTextInputLayout == null) {
        break missingId;
      }

      id = R.id.txtRegisterSwitchText;
      TextView txtRegisterSwitchText = ViewBindings.findChildViewById(rootView, id);
      if (txtRegisterSwitchText == null) {
        break missingId;
      }

      return new ActivityLoginBinding((LinearLayout) rootView, btnLogin, editPassword, editUserName,
          forgotPasswordText, searchTextInputLayou, searchTextInputLayout, txtRegisterSwitchText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
