// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainNewBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final AppCompatButton btnRefreshTransList;

  @NonNull
  public final CardView cardViewMyCart;

  @NonNull
  public final CardView cardViewOrderHistory;

  @NonNull
  public final LinearLayout llNoRecordsBookingHistory;

  @NonNull
  public final RecyclerView recycleViewBookingHistory;

  private ActivityMainNewBinding(@NonNull LinearLayout rootView,
      @NonNull AppCompatButton btnRefreshTransList, @NonNull CardView cardViewMyCart,
      @NonNull CardView cardViewOrderHistory, @NonNull LinearLayout llNoRecordsBookingHistory,
      @NonNull RecyclerView recycleViewBookingHistory) {
    this.rootView = rootView;
    this.btnRefreshTransList = btnRefreshTransList;
    this.cardViewMyCart = cardViewMyCart;
    this.cardViewOrderHistory = cardViewOrderHistory;
    this.llNoRecordsBookingHistory = llNoRecordsBookingHistory;
    this.recycleViewBookingHistory = recycleViewBookingHistory;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainNewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainNewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main_new, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainNewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnRefreshTransList;
      AppCompatButton btnRefreshTransList = ViewBindings.findChildViewById(rootView, id);
      if (btnRefreshTransList == null) {
        break missingId;
      }

      id = R.id.cardViewMyCart;
      CardView cardViewMyCart = ViewBindings.findChildViewById(rootView, id);
      if (cardViewMyCart == null) {
        break missingId;
      }

      id = R.id.cardViewOrderHistory;
      CardView cardViewOrderHistory = ViewBindings.findChildViewById(rootView, id);
      if (cardViewOrderHistory == null) {
        break missingId;
      }

      id = R.id.llNoRecordsBookingHistory;
      LinearLayout llNoRecordsBookingHistory = ViewBindings.findChildViewById(rootView, id);
      if (llNoRecordsBookingHistory == null) {
        break missingId;
      }

      id = R.id.recycleViewBookingHistory;
      RecyclerView recycleViewBookingHistory = ViewBindings.findChildViewById(rootView, id);
      if (recycleViewBookingHistory == null) {
        break missingId;
      }

      return new ActivityMainNewBinding((LinearLayout) rootView, btnRefreshTransList,
          cardViewMyCart, cardViewOrderHistory, llNoRecordsBookingHistory,
          recycleViewBookingHistory);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
