// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityTransactionStatusBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final AppCompatButton btnDone;

  @NonNull
  public final ImageView imageTransStatus;

  @NonNull
  public final TextView txtPaymentStatus;

  private ActivityTransactionStatusBinding(@NonNull RelativeLayout rootView,
      @NonNull AppCompatButton btnDone, @NonNull ImageView imageTransStatus,
      @NonNull TextView txtPaymentStatus) {
    this.rootView = rootView;
    this.btnDone = btnDone;
    this.imageTransStatus = imageTransStatus;
    this.txtPaymentStatus = txtPaymentStatus;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityTransactionStatusBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityTransactionStatusBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_transaction_status, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityTransactionStatusBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnDone;
      AppCompatButton btnDone = ViewBindings.findChildViewById(rootView, id);
      if (btnDone == null) {
        break missingId;
      }

      id = R.id.imageTransStatus;
      ImageView imageTransStatus = ViewBindings.findChildViewById(rootView, id);
      if (imageTransStatus == null) {
        break missingId;
      }

      id = R.id.txtPaymentStatus;
      TextView txtPaymentStatus = ViewBindings.findChildViewById(rootView, id);
      if (txtPaymentStatus == null) {
        break missingId;
      }

      return new ActivityTransactionStatusBinding((RelativeLayout) rootView, btnDone,
          imageTransStatus, txtPaymentStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
