// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityForgotPasswordBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextInputLayout TextInputLayoutConPass;

  @NonNull
  public final TextInputLayout TextInputLayoutMob;

  @NonNull
  public final AppCompatButton btnRegister;

  @NonNull
  public final TextInputEditText editConfPassword;

  @NonNull
  public final TextInputEditText editHolderName;

  @NonNull
  public final TextInputEditText editMobile;

  @NonNull
  public final TextInputEditText editPassword;

  @NonNull
  public final TextInputLayout searchTextInputLayou;

  @NonNull
  public final TextInputLayout searchTextInputLayout;

  @NonNull
  public final TextView txtLoginSwitchText;

  private ActivityForgotPasswordBinding(@NonNull LinearLayout rootView,
      @NonNull TextInputLayout TextInputLayoutConPass, @NonNull TextInputLayout TextInputLayoutMob,
      @NonNull AppCompatButton btnRegister, @NonNull TextInputEditText editConfPassword,
      @NonNull TextInputEditText editHolderName, @NonNull TextInputEditText editMobile,
      @NonNull TextInputEditText editPassword, @NonNull TextInputLayout searchTextInputLayou,
      @NonNull TextInputLayout searchTextInputLayout, @NonNull TextView txtLoginSwitchText) {
    this.rootView = rootView;
    this.TextInputLayoutConPass = TextInputLayoutConPass;
    this.TextInputLayoutMob = TextInputLayoutMob;
    this.btnRegister = btnRegister;
    this.editConfPassword = editConfPassword;
    this.editHolderName = editHolderName;
    this.editMobile = editMobile;
    this.editPassword = editPassword;
    this.searchTextInputLayou = searchTextInputLayou;
    this.searchTextInputLayout = searchTextInputLayout;
    this.txtLoginSwitchText = txtLoginSwitchText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityForgotPasswordBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityForgotPasswordBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_forgot_password, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityForgotPasswordBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.TextInputLayoutConPass;
      TextInputLayout TextInputLayoutConPass = ViewBindings.findChildViewById(rootView, id);
      if (TextInputLayoutConPass == null) {
        break missingId;
      }

      id = R.id.TextInputLayoutMob;
      TextInputLayout TextInputLayoutMob = ViewBindings.findChildViewById(rootView, id);
      if (TextInputLayoutMob == null) {
        break missingId;
      }

      id = R.id.btnRegister;
      AppCompatButton btnRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnRegister == null) {
        break missingId;
      }

      id = R.id.editConfPassword;
      TextInputEditText editConfPassword = ViewBindings.findChildViewById(rootView, id);
      if (editConfPassword == null) {
        break missingId;
      }

      id = R.id.editHolderName;
      TextInputEditText editHolderName = ViewBindings.findChildViewById(rootView, id);
      if (editHolderName == null) {
        break missingId;
      }

      id = R.id.editMobile;
      TextInputEditText editMobile = ViewBindings.findChildViewById(rootView, id);
      if (editMobile == null) {
        break missingId;
      }

      id = R.id.editPassword;
      TextInputEditText editPassword = ViewBindings.findChildViewById(rootView, id);
      if (editPassword == null) {
        break missingId;
      }

      id = R.id.searchTextInputLayou;
      TextInputLayout searchTextInputLayou = ViewBindings.findChildViewById(rootView, id);
      if (searchTextInputLayou == null) {
        break missingId;
      }

      id = R.id.searchTextInputLayout;
      TextInputLayout searchTextInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (searchTextInputLayout == null) {
        break missingId;
      }

      id = R.id.txtLoginSwitchText;
      TextView txtLoginSwitchText = ViewBindings.findChildViewById(rootView, id);
      if (txtLoginSwitchText == null) {
        break missingId;
      }

      return new ActivityForgotPasswordBinding((LinearLayout) rootView, TextInputLayoutConPass,
          TextInputLayoutMob, btnRegister, editConfPassword, editHolderName, editMobile,
          editPassword, searchTextInputLayou, searchTextInputLayout, txtLoginSwitchText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
