// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMyBooksBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LinearLayout llNoRecordsBI;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final RecyclerView recycleViewBI;

  private ActivityMyBooksBinding(@NonNull ConstraintLayout rootView,
      @NonNull LinearLayout llNoRecordsBI, @NonNull ConstraintLayout main,
      @NonNull RecyclerView recycleViewBI) {
    this.rootView = rootView;
    this.llNoRecordsBI = llNoRecordsBI;
    this.main = main;
    this.recycleViewBI = recycleViewBI;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMyBooksBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMyBooksBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_my_books, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMyBooksBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.llNoRecordsBI;
      LinearLayout llNoRecordsBI = ViewBindings.findChildViewById(rootView, id);
      if (llNoRecordsBI == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.recycleViewBI;
      RecyclerView recycleViewBI = ViewBindings.findChildViewById(rootView, id);
      if (recycleViewBI == null) {
        break missingId;
      }

      return new ActivityMyBooksBinding((ConstraintLayout) rootView, llNoRecordsBI, main,
          recycleViewBI);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
