// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import com.akash.booklibrary.utils.scanner.ml.ui.CameraSourcePreview;
import com.akash.booklibrary.utils.scanner.ml.ui.GraphicOverlay;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBarCodeMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LinearLayout control;

  @NonNull
  public final GraphicOverlay graphicOverlay;

  @NonNull
  public final ImageView imgCancelScan;

  @NonNull
  public final ImageView imgScannerAutoFocus;

  @NonNull
  public final ImageView imgScannerFlash;

  @NonNull
  public final CameraSourcePreview preview;

  @NonNull
  public final ConstraintLayout root;

  @NonNull
  public final TextView txtScanQRHeader;

  private ActivityBarCodeMainBinding(@NonNull ConstraintLayout rootView,
      @NonNull LinearLayout control, @NonNull GraphicOverlay graphicOverlay,
      @NonNull ImageView imgCancelScan, @NonNull ImageView imgScannerAutoFocus,
      @NonNull ImageView imgScannerFlash, @NonNull CameraSourcePreview preview,
      @NonNull ConstraintLayout root, @NonNull TextView txtScanQRHeader) {
    this.rootView = rootView;
    this.control = control;
    this.graphicOverlay = graphicOverlay;
    this.imgCancelScan = imgCancelScan;
    this.imgScannerAutoFocus = imgScannerAutoFocus;
    this.imgScannerFlash = imgScannerFlash;
    this.preview = preview;
    this.root = root;
    this.txtScanQRHeader = txtScanQRHeader;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBarCodeMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBarCodeMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_bar_code_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBarCodeMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.control;
      LinearLayout control = ViewBindings.findChildViewById(rootView, id);
      if (control == null) {
        break missingId;
      }

      id = R.id.graphicOverlay;
      GraphicOverlay graphicOverlay = ViewBindings.findChildViewById(rootView, id);
      if (graphicOverlay == null) {
        break missingId;
      }

      id = R.id.img_cancel_scan;
      ImageView imgCancelScan = ViewBindings.findChildViewById(rootView, id);
      if (imgCancelScan == null) {
        break missingId;
      }

      id = R.id.img_scanner_auto_focus;
      ImageView imgScannerAutoFocus = ViewBindings.findChildViewById(rootView, id);
      if (imgScannerAutoFocus == null) {
        break missingId;
      }

      id = R.id.img_scanner_flash;
      ImageView imgScannerFlash = ViewBindings.findChildViewById(rootView, id);
      if (imgScannerFlash == null) {
        break missingId;
      }

      id = R.id.preview;
      CameraSourcePreview preview = ViewBindings.findChildViewById(rootView, id);
      if (preview == null) {
        break missingId;
      }

      ConstraintLayout root = (ConstraintLayout) rootView;

      id = R.id.txtScanQRHeader;
      TextView txtScanQRHeader = ViewBindings.findChildViewById(rootView, id);
      if (txtScanQRHeader == null) {
        break missingId;
      }

      return new ActivityBarCodeMainBinding((ConstraintLayout) rootView, control, graphicOverlay,
          imgCancelScan, imgScannerAutoFocus, imgScannerFlash, preview, root, txtScanQRHeader);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
