// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentBookReturnedBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final LinearLayout llNoRecordsBReturned;

  @NonNull
  public final RecyclerView recycleViewBReturned;

  private FragmentBookReturnedBinding(@NonNull FrameLayout rootView,
      @NonNull LinearLayout llNoRecordsBReturned, @NonNull RecyclerView recycleViewBReturned) {
    this.rootView = rootView;
    this.llNoRecordsBReturned = llNoRecordsBReturned;
    this.recycleViewBReturned = recycleViewBReturned;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentBookReturnedBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentBookReturnedBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_book_returned, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentBookReturnedBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.llNoRecordsBReturned;
      LinearLayout llNoRecordsBReturned = ViewBindings.findChildViewById(rootView, id);
      if (llNoRecordsBReturned == null) {
        break missingId;
      }

      id = R.id.recycleViewBReturned;
      RecyclerView recycleViewBReturned = ViewBindings.findChildViewById(rootView, id);
      if (recycleViewBReturned == null) {
        break missingId;
      }

      return new FragmentBookReturnedBinding((FrameLayout) rootView, llNoRecordsBReturned,
          recycleViewBReturned);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
