// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentBookReturnReqBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final LinearLayout llNoRecordsBRR;

  @NonNull
  public final RecyclerView recycleViewBRR;

  private FragmentBookReturnReqBinding(@NonNull FrameLayout rootView,
      @NonNull LinearLayout llNoRecordsBRR, @NonNull RecyclerView recycleViewBRR) {
    this.rootView = rootView;
    this.llNoRecordsBRR = llNoRecordsBRR;
    this.recycleViewBRR = recycleViewBRR;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentBookReturnReqBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentBookReturnReqBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_book_return_req, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentBookReturnReqBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.llNoRecordsBRR;
      LinearLayout llNoRecordsBRR = ViewBindings.findChildViewById(rootView, id);
      if (llNoRecordsBRR == null) {
        break missingId;
      }

      id = R.id.recycleViewBRR;
      RecyclerView recycleViewBRR = ViewBindings.findChildViewById(rootView, id);
      if (recycleViewBRR == null) {
        break missingId;
      }

      return new FragmentBookReturnReqBinding((FrameLayout) rootView, llNoRecordsBRR,
          recycleViewBRR);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
