// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentBookRequestBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final LinearLayout llNoRecordsBR;

  @NonNull
  public final RecyclerView recycleViewBR;

  private FragmentBookRequestBinding(@NonNull FrameLayout rootView,
      @NonNull LinearLayout llNoRecordsBR, @NonNull RecyclerView recycleViewBR) {
    this.rootView = rootView;
    this.llNoRecordsBR = llNoRecordsBR;
    this.recycleViewBR = recycleViewBR;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentBookRequestBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentBookRequestBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_book_request, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentBookRequestBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.llNoRecordsBR;
      LinearLayout llNoRecordsBR = ViewBindings.findChildViewById(rootView, id);
      if (llNoRecordsBR == null) {
        break missingId;
      }

      id = R.id.recycleViewBR;
      RecyclerView recycleViewBR = ViewBindings.findChildViewById(rootView, id);
      if (recycleViewBR == null) {
        break missingId;
      }

      return new FragmentBookRequestBinding((FrameLayout) rootView, llNoRecordsBR, recycleViewBR);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
