// Generated by view binder compiler. Do not edit!
package com.akash.booklibrary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akash.booklibrary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemMyBooksNewBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final ImageView imgProviderLogo;

  @NonNull
  public final LinearLayout llDate;

  @NonNull
  public final LinearLayout llStatus;

  @NonNull
  public final TextView txtBookAuthor;

  @NonNull
  public final TextView txtBookName;

  @NonNull
  public final TextView txtBookStatus;

  @NonNull
  public final TextView txtBookType;

  @NonNull
  public final TextView txtDateHeader;

  @NonNull
  public final TextView txtIssueDate;

  private ItemMyBooksNewBinding(@NonNull CardView rootView, @NonNull ImageView imgProviderLogo,
      @NonNull LinearLayout llDate, @NonNull LinearLayout llStatus, @NonNull TextView txtBookAuthor,
      @NonNull TextView txtBookName, @NonNull TextView txtBookStatus, @NonNull TextView txtBookType,
      @NonNull TextView txtDateHeader, @NonNull TextView txtIssueDate) {
    this.rootView = rootView;
    this.imgProviderLogo = imgProviderLogo;
    this.llDate = llDate;
    this.llStatus = llStatus;
    this.txtBookAuthor = txtBookAuthor;
    this.txtBookName = txtBookName;
    this.txtBookStatus = txtBookStatus;
    this.txtBookType = txtBookType;
    this.txtDateHeader = txtDateHeader;
    this.txtIssueDate = txtIssueDate;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemMyBooksNewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemMyBooksNewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_my_books_new, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemMyBooksNewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imgProviderLogo;
      ImageView imgProviderLogo = ViewBindings.findChildViewById(rootView, id);
      if (imgProviderLogo == null) {
        break missingId;
      }

      id = R.id.llDate;
      LinearLayout llDate = ViewBindings.findChildViewById(rootView, id);
      if (llDate == null) {
        break missingId;
      }

      id = R.id.llStatus;
      LinearLayout llStatus = ViewBindings.findChildViewById(rootView, id);
      if (llStatus == null) {
        break missingId;
      }

      id = R.id.txtBookAuthor;
      TextView txtBookAuthor = ViewBindings.findChildViewById(rootView, id);
      if (txtBookAuthor == null) {
        break missingId;
      }

      id = R.id.txtBookName;
      TextView txtBookName = ViewBindings.findChildViewById(rootView, id);
      if (txtBookName == null) {
        break missingId;
      }

      id = R.id.txtBookStatus;
      TextView txtBookStatus = ViewBindings.findChildViewById(rootView, id);
      if (txtBookStatus == null) {
        break missingId;
      }

      id = R.id.txtBookType;
      TextView txtBookType = ViewBindings.findChildViewById(rootView, id);
      if (txtBookType == null) {
        break missingId;
      }

      id = R.id.txtDateHeader;
      TextView txtDateHeader = ViewBindings.findChildViewById(rootView, id);
      if (txtDateHeader == null) {
        break missingId;
      }

      id = R.id.txtIssueDate;
      TextView txtIssueDate = ViewBindings.findChildViewById(rootView, id);
      if (txtIssueDate == null) {
        break missingId;
      }

      return new ItemMyBooksNewBinding((CardView) rootView, imgProviderLogo, llDate, llStatus,
          txtBookAuthor, txtBookName, txtBookStatus, txtBookType, txtDateHeader, txtIssueDate);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
